<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain7.xml"
		unuid="1683306423150.637324812.1062956851"
		mipmaps_folder="10x__RGB__x4/trakem2.1683306423150.637324812.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x4/"
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
		first_mipmap_level_saved="0"
	>
		<anything id="678" title="thal" expanded="true">
			<ball id="685" oid="684"/>
			<area_list id="687" oid="686"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3248.0"
		layer_height="2312.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="684"
			width="1621.3334"
			height="870.0"
			transform="matrix(1.0,0.0,0.0,1.0,793.3333333333335,552.9999999999999)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="827.6666666666667" y="418.0" layer_id="132" r="13.333333333333334" />
			<t2_ball_ob x="784.3333333333334" y="856.6666666666667" layer_id="234" r="13.333333333333334" />
			<t2_ball_ob x="782.0000000000001" y="244.66666666666669" layer_id="264" r="13.333333333333334" />
			<t2_ball_ob x="809.6666666666667" y="13.333333333333334" layer_id="372" r="13.333333333333334" />
			<t2_ball_ob x="794.6666666666667" y="334.0" layer_id="366" r="13.333333333333334" />
			<t2_ball_ob x="48.66666666666667" y="597.0" layer_id="435" r="13.333333333333334" />
			<t2_ball_ob x="1539.3333333333333" y="602.0" layer_id="429" r="13.333333333333334" />
			<t2_ball_ob x="13.333333333333334" y="825.0" layer_id="384" r="13.333333333333334" />
			<t2_ball_ob x="1608.0" y="807.0" layer_id="375" r="13.333333333333334" />
		</t2_ball>
		<t2_area_list
			oid="686"
			width="872.0"
			height="1132.0"
			transform="matrix(1.0,0.0,0.0,1.0,1568.0,559.0)"
			locked="true"
			title="rect"
			links="236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443,446,449,452,455,458,461,464,467,470,473,476,479,482,676"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 42 124 L 42 1104 L 870 1104 L 870 124 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 6 334 L 6 862 L 528 862 L 528 334 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 42 122 L 42 1106 L 868 1106 L 868 122 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 10 314 L 10 874 L 536 874 L 536 314 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 44 108 L 44 1110 L 872 1110 L 872 108 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 6 310 L 6 882 L 548 882 L 548 310 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 36 102 L 36 1118 L 854 1118 L 854 102 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 12 304 L 12 898 L 580 898 L 580 304 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 40 102 L 40 1132 L 812 1132 L 812 102 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 2 286 L 2 890 L 600 890 L 600 286 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 38 80 L 38 1116 L 814 1116 L 814 80 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 2 274 L 2 904 L 602 904 L 602 274 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 30 76 L 30 1110 L 842 1110 L 842 76 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 4 268 L 4 910 L 618 910 L 618 268 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 38 90 L 38 1082 L 836 1082 L 836 90 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 0 262 L 0 916 L 632 916 L 632 262 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 32 108 L 32 1084 L 824 1084 L 824 108 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 2 262 L 2 930 L 634 930 L 634 262 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 24 86 L 24 1058 L 798 1058 L 798 86 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 2 242 L 2 922 L 686 922 L 686 242 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 32 86 L 32 1086 L 818 1086 L 818 86 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 10 246 L 10 946 L 704 946 L 704 246 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 36 86 L 36 1052 L 810 1052 L 810 86 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 10 240 L 10 942 L 708 942 L 708 240 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 32 72 L 32 1058 L 798 1058 L 798 72 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 18 228 L 18 954 L 722 954 L 722 228 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 24 68 L 24 1058 L 794 1058 L 794 68 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 16 228 L 16 958 L 726 958 L 726 228 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 30 74 L 30 1050 L 774 1050 L 774 74 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 14 222 L 14 958 L 738 958 L 738 222 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 32 60 L 32 1040 L 772 1040 L 772 60 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 14 236 L 14 972 L 748 972 L 748 236 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 32 64 L 32 1066 L 758 1066 L 758 64 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 22 228 L 22 978 L 756 978 L 756 228 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 32 60 L 32 1042 L 760 1042 L 760 60 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 22 230 L 22 982 L 762 982 L 762 230 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 24 56 L 24 1066 L 736 1066 L 736 56 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 28 238 L 28 998 L 778 998 L 778 238 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 18 52 L 18 1058 L 734 1058 L 734 52 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 26 240 L 26 996 L 780 996 L 780 240 z" />
			</t2_area>
			<t2_area layer_id="444">
				<t2_path d="M 18 46 L 18 1052 L 734 1052 L 734 46 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 26 240 L 26 1004 L 794 1004 L 794 240 z" />
			</t2_area>
			<t2_area layer_id="447">
				<t2_path d="M 16 42 L 16 1056 L 742 1056 L 742 42 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 26 246 L 26 1018 L 812 1018 L 812 246 z" />
			</t2_area>
			<t2_area layer_id="450">
				<t2_path d="M 20 76 L 20 1074 L 744 1074 L 744 76 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 24 240 L 24 1020 L 822 1020 L 822 240 z" />
			</t2_area>
			<t2_area layer_id="453">
				<t2_path d="M 22 42 L 22 1064 L 748 1064 L 748 42 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 24 242 L 24 1068 L 828 1068 L 828 242 z" />
			</t2_area>
			<t2_area layer_id="456">
				<t2_path d="M 18 46 L 18 1052 L 754 1052 L 754 46 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 28 242 L 28 1064 L 824 1064 L 824 242 z" />
			</t2_area>
			<t2_area layer_id="459">
				<t2_path d="M 4 30 L 4 1042 L 752 1042 L 752 30 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 28 242 L 28 1080 L 830 1080 L 830 242 z" />
			</t2_area>
			<t2_area layer_id="462">
				<t2_path d="M 26 20 L 26 1036 L 758 1036 L 758 20 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 38 242 L 38 1084 L 836 1084 L 836 242 z" />
			</t2_area>
			<t2_area layer_id="465">
				<t2_path d="M 20 12 L 20 1034 L 770 1034 L 770 12 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 34 244 L 34 1080 L 838 1080 L 838 244 z" />
			</t2_area>
			<t2_area layer_id="468">
				<t2_path d="M 18 24 L 18 1014 L 740 1014 L 740 24 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 34 240 L 34 1082 L 850 1082 L 850 240 z" />
			</t2_area>
			<t2_area layer_id="471">
				<t2_path d="M 18 32 L 18 1020 L 676 1020 L 676 32 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 32 236 L 32 1080 L 856 1080 L 856 236 z" />
			</t2_area>
			<t2_area layer_id="474">
				<t2_path d="M 16 18 L 16 1030 L 660 1030 L 660 18 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 36 238 L 36 1080 L 852 1080 L 852 238 z" />
			</t2_area>
			<t2_area layer_id="477">
				<t2_path d="M 22 6 L 22 1036 L 664 1036 L 664 6 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 32 240 L 32 1088 L 860 1088 L 860 240 z" />
			</t2_area>
			<t2_area layer_id="480">
				<t2_path d="M 20 0 L 20 1038 L 656 1038 L 656 0 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 32 230 L 32 1080 L 858 1080 L 858 230 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 30 234 L 30 1102 L 838 1102 L 838 234 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 30 208 L 30 1090 L 836 1090 L 836 208 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 12 554 L 12 692 L 234 692 L 234 554 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 36 206 L 36 1100 L 840 1100 L 840 206 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 10 488 L 10 708 L 358 708 L 358 488 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 20 194 L 20 1104 L 840 1104 L 840 194 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 12 464 L 12 732 L 382 732 L 382 464 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 26 178 L 26 1098 L 852 1098 L 852 178 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 26 450 L 26 774 L 406 774 L 406 450 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 30 162 L 30 1104 L 858 1104 L 858 162 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 12 426 L 12 792 L 468 792 L 468 426 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 38 154 L 38 1106 L 870 1106 L 870 154 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 12 370 L 12 802 L 504 802 L 504 370 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 38 148 L 38 1104 L 872 1104 L 872 148 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 12 348 L 12 832 L 512 832 L 512 348 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 38 138 L 38 1106 L 870 1106 L 870 138 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 12 334 L 12 836 L 510 836 L 510 334 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="40.0"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1561.0"
				height="1099.0"
				transform="matrix(0.9951181891170792,-0.09869037282503727,0.09869037282503727,0.9951181891170792,832.674775544453,584.3223086444741)"
				locked="true"
				title="Brain7_001_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_001_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1561"
				o_height="1099"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="40.0"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1555.0"
				height="1108.0"
				transform="matrix(0.9968361686932239,-0.07948366363608626,0.07948366363608626,0.9968361686932239,833.1973817303051,565.4714378273675)"
				locked="true"
				title="Brain7_002_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_002_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1555"
				o_height="1108"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="40.0"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1612.0"
				height="1146.0"
				transform="matrix(0.9944430210832543,-0.10527619777903297,0.10527619777903297,0.9944430210832543,806.9005494389476,560.6616056109278)"
				locked="true"
				title="Brain7_003_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_003_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1612"
				o_height="1146"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="40.0"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1645.0"
				height="1170.0"
				transform="matrix(0.9999460813600496,-0.010384333039779443,0.010384333039779443,0.9999460813600496,820.8681978127097,479.972465180012)"
				locked="true"
				title="Brain7_004_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_004_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1645"
				o_height="1170"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="40.0"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1645.0"
				height="1212.0"
				transform="matrix(0.9985772818877721,-0.053323654203637036,0.053323654203637036,0.9985772818877721,803.7515331023615,496.0136580571948)"
				locked="true"
				title="Brain7_005_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_005_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1645"
				o_height="1212"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="40.0"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1659.0"
				height="1208.0"
				transform="matrix(0.996738915547678,-0.08069407805309292,0.08069407805309292,0.996738915547678,779.9862899104501,517.2117812965434)"
				locked="true"
				title="Brain7_006_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_006_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1659"
				o_height="1208"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="40.0"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="26"
				width="1678.0"
				height="1208.0"
				transform="matrix(0.9977662016895269,-0.0668027451984909,0.0668027451984909,0.9977662016895269,781.1512192230148,507.50281359242126)"
				locked="true"
				title="Brain7_007_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_007_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1678"
				o_height="1208"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="7"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="40.0"
			 z="88.10560000000001"
			 title="sec#08"
		>
			<t2_patch
				oid="29"
				width="1689.0"
				height="1200.0"
				transform="matrix(0.9957219373126001,-0.09240034390868164,0.09240034390868164,0.9957219373126001,764.3367358466603,530.0461819233974)"
				locked="true"
				title="Brain7_008_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain7_008_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1689"
				o_height="1200"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="8"
			>
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="30"
			 thickness="40.0"