<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain11.xml"
		unuid="1698214157115.1660387868.1062956851"
		mipmaps_folder="10x__RGB__x4/trakem2.1698214157115.1660387868.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x4/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="675" title="thal" expanded="true">
			<ball id="680" oid="679"/>
			<area_list id="683" oid="682"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3044.0"
		layer_height="2317.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="679"
			width="1542.0"
			height="918.0"
			transform="matrix(1.0,0.0,0.0,1.0,722.0,644.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="730.0" y="532.0" layer_id="78" r="20.0" />
			<t2_ball_ob x="756.0" y="898.0" layer_id="183" r="20.0" />
			<t2_ball_ob x="782.0" y="282.0" layer_id="219" r="20.0" />
			<t2_ball_ob x="780.0" y="20.0" layer_id="330" r="20.0" />
			<t2_ball_ob x="778.0" y="314.0" layer_id="321" r="20.0" />
			<t2_ball_ob x="58.0" y="508.0" layer_id="387" r="20.0" />
			<t2_ball_ob x="1516.0" y="560.0" layer_id="369" r="20.0" />
			<t2_ball_ob x="20.0" y="730.0" layer_id="333" r="20.0" />
			<t2_ball_ob x="1522.0" y="816.0" layer_id="318" r="20.0" />
		</t2_ball>
		<t2_area_list
			oid="682"
			width="814.0"
			height="1098.0"
			transform="matrix(1.0,0.0,0.0,1.0,1480.0,590.0)"
			title="rect"
			links="188,191,197,200,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 24 110 L 24 1086 L 748 1086 L 748 110 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 14 350 L 14 1010 L 732 1010 L 732 350 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 24 94 L 24 1070 L 748 1070 L 748 94 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 14 352 L 14 1010 L 740 1010 L 740 352 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 24 88 L 24 1056 L 752 1056 L 752 88 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 14 352 L 14 1016 L 746 1016 L 746 352 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 22 84 L 22 1058 L 746 1058 L 746 84 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 16 354 L 16 1026 L 756 1026 L 756 354 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 22 82 L 22 1068 L 750 1068 L 750 82 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 16 348 L 16 1028 L 760 1028 L 760 348 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 24 76 L 24 1036 L 744 1036 L 744 76 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 18 346 L 18 1032 L 762 1032 L 762 346 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 24 60 L 24 1040 L 728 1040 L 728 60 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 16 342 L 16 1036 L 770 1036 L 770 342 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 22 52 L 22 1034 L 740 1034 L 740 52 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 14 340 L 14 1072 L 764 1072 L 764 340 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 26 20 L 26 1002 L 724 1002 L 724 20 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 14 340 L 14 1076 L 778 1076 L 778 340 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 26 16 L 26 966 L 712 966 L 712 16 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 18 328 L 18 1076 L 780 1076 L 780 328 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 26 2 L 26 972 L 666 972 L 666 2 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 18 328 L 18 1080 L 788 1080 L 788 328 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 26 4 L 26 978 L 658 978 L 658 4 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 22 334 L 22 1076 L 764 1076 L 764 334 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 26 0 L 26 968 L 648 968 L 648 0 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 22 324 L 22 1072 L 774 1072 L 774 324 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 18 316 L 18 1086 L 770 1086 L 770 316 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 22 310 L 22 1074 L 770 1074 L 770 310 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 14 318 L 14 1080 L 768 1080 L 768 318 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 14 314 L 14 1086 L 774 1086 L 774 314 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 22 286 L 22 1076 L 784 1076 L 784 286 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 20 268 L 20 1084 L 792 1084 L 792 268 z" />
			</t2_area>
			<t2_area layer_id="186">
				<t2_path d="M 6 670 L 6 812 L 334 812 L 334 670 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 22 262 L 22 1090 L 798 1090 L 798 262 z" />
			</t2_area>
			<t2_area layer_id="189">
				<t2_path d="M 0 628 L 0 856 L 372 856 L 372 628 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 18 254 L 18 1096 L 804 1096 L 804 254 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 20 242 L 20 1098 L 810 1098 L 810 242 z" />
			</t2_area>
			<t2_area layer_id="195">
				<t2_path d="M 0 594 L 0 902 L 440 902 L 440 594 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 16 220 L 16 1092 L 814 1092 L 814 220 z" />
			</t2_area>
			<t2_area layer_id="198">
				<t2_path d="M 2 572 L 2 916 L 466 916 L 466 572 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 14 214 L 14 1092 L 810 1092 L 810 214 z" />
			</t2_area>
			<t2_area layer_id="201">
				<t2_path d="M 2 538 L 2 924 L 496 924 L 496 538 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 14 196 L 14 1090 L 808 1090 L 808 196 z" />
			</t2_area>
			<t2_area layer_id="204">
				<t2_path d="M 2 518 L 2 940 L 510 940 L 510 518 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 14 190 L 14 1092 L 802 1092 L 802 190 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 2 500 L 2 950 L 534 950 L 534 500 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 18 174 L 18 1090 L 802 1090 L 802 174 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 2 488 L 2 956 L 556 956 L 556 488 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 18 168 L 18 1084 L 800 1084 L 800 168 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 2 472 L 2 960 L 568 960 L 568 472 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 22 144 L 22 1082 L 800 1082 L 800 144 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 2 462 L 2 970 L 592 970 L 592 462 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 26 132 L 26 1072 L 784 1072 L 784 132 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 2 456 L 2 972 L 598 972 L 598 456 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 26 128 L 26 1074 L 788 1074 L 788 128 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 2 444 L 2 978 L 606 978 L 606 444 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 26 122 L 26 1074 L 778 1074 L 778 122 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 12 430 L 12 978 L 622 978 L 622 430 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 26 118 L 26 1066 L 780 1066 L 780 118 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 12 424 L 12 986 L 638 986 L 638 424 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 26 116 L 26 1064 L 784 1064 L 784 116 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 12 416 L 12 986 L 654 986 L 654 416 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 30 104 L 30 1054 L 782 1054 L 782 104 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 12 404 L 12 992 L 666 992 L 666 404 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 28 134 L 28 1064 L 782 1064 L 782 134 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 12 398 L 12 998 L 672 998 L 672 398 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 28 134 L 28 1080 L 770 1080 L 770 134 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 12 394 L 12 1002 L 676 1002 L 676 394 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 28 128 L 28 1078 L 750 1078 L 750 128 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 10 386 L 10 1004 L 684 1004 L 684 386 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 26 124 L 26 1086 L 746 1086 L 746 124 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 12 384 L 12 1004 L 694 1004 L 694 384 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 26 130 L 26 1084 L 756 1084 L 756 130 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 10 370 L 10 1000 L 704 1000 L 704 370 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 26 116 L 26 1084 L 750 1084 L 750 116 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 12 368 L 12 1012 L 716 1012 L 716 368 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 16 120 L 16 1092 L 730 1092 L 730 120 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 12 362 L 12 1008 L 724 1008 L 724 362 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="11.0132"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1802.0"
				height="1357.0"
				transform="matrix(0.9979028347175326,0.064729687698757,-0.064729687698757,0.9979028347175326,597.7883848759363,547.1504673955577)"
				title="Brain11_001_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_001_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1802"
				o_height="1357"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="11.0132"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1818.0"
				height="1344.0"
				transform="matrix(0.9999234441991551,0.00975873991146285,-0.00975873991146285,0.9999234441991551,560.0853940833945,607.6632504278274)"
				title="Brain11_002_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_002_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1818"
				o_height="1344"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="11.0132"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1860.0"
				height="1277.0"
				transform="matrix(0.9987901917800056,0.04904181097323404,-0.04904181097323404,0.9987901917800056,567.4391931858509,552.4785456331989)"
				title="Brain11_003_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_003_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1860"
				o_height="1277"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="11.0132"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1860.0"
				height="1301.0"
				transform="matrix(0.9972958689944244,0.07172542224306246,-0.07172542224306246,0.9972958689944244,589.1912809872683,527.0946377451165)"
				title="Brain11_004_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_004_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1860"
				o_height="1301"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="11.0132"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1869.0"
				height="1317.0"
				transform="matrix(0.998902685849539,-0.04669079447692513,0.04669079447692513,0.998902685849539,520.5419603804162,608.1683349077731)"
				title="Brain11_005_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_005_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1869"
				o_height="1317"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="11.0132"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1887.0"
				height="1317.0"
				transform="matrix(0.9975402134629734,-0.06866454565033452,0.06866454565033452,0.9975402134629734,487.8394417923452,645.9867736752595)"
				title="Brain11_006_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_006_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1887"
				o_height="1317"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="11.0132"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="26"
				width="1928.0"
				height="1335.0"
				transform="matrix(0.9989928963711069,-0.04462891355902455,0.04462891355902455,0.9989928963711069,486.71992954492765,610.4194615975339)"
				title="Brain11_007_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_007_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1928"
				o_height="1335"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="7"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="11.0132"
			 z="88.10560000000001"
			 title="sec#08"
		>
			<t2_patch
				oid="29"
				width="1928.0"
				height="1344.0"
				transform="matrix(0.9994613229505489,-0.03261070279003056,0.03261070279003056,0.9994613229505489,493.0177253827662,597.9652880035829)"
				title="Brain11_008_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain11_008_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1928"
				o_height="1344"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="8"
			>