<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain10.xml"
		unuid="1698214105126.1127027619.1062956851"
		mipmaps_folder="10x__RGB__x4/trakem2.1698214105126.1127027619.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x4/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="702" title="thal" expanded="true">
			<ball id="707" oid="706"/>
			<area_list id="710" oid="709"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2965.0"
		layer_height="2084.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="706"
			width="1618.0"
			height="878.0"
			transform="matrix(1.0,0.0,0.0,1.0,645.0,579.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="800.0" y="434.0" layer_id="99" r="20.0" />
			<t2_ball_ob x="788.0" y="858.0" layer_id="207" r="20.0" />
			<t2_ball_ob x="794.0" y="254.0" layer_id="231" r="20.0" />
			<t2_ball_ob x="818.0" y="20.0" layer_id="333" r="20.0" />
			<t2_ball_ob x="814.0" y="346.0" layer_id="330" r="20.0" />
			<t2_ball_ob x="92.0" y="560.0" layer_id="387" r="20.0" />
			<t2_ball_ob x="1530.0" y="544.0" layer_id="393" r="20.0" />
			<t2_ball_ob x="20.0" y="822.0" layer_id="339" r="20.0" />
			<t2_ball_ob x="1598.0" y="782.0" layer_id="345" r="20.0" />
		</t2_ball>
		<t2_area_list
			oid="709"
			width="846.0"
			height="1140.0"
			transform="matrix(1.0,0.0,0.0,1.0,1427.0,503.0)"
			title="rect"
			links="206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443,446,449"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 46 166 L 46 1084 L 784 1084 L 784 166 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 26 386 L 26 986 L 686 986 L 686 386 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 46 158 L 46 1084 L 780 1084 L 780 158 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 24 380 L 24 994 L 692 994 L 692 380 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 46 158 L 46 1090 L 770 1090 L 770 158 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 24 374 L 24 1002 L 710 1002 L 710 374 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 46 144 L 46 1098 L 758 1098 L 758 144 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 26 364 L 26 1008 L 716 1008 L 716 364 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 46 138 L 46 1072 L 750 1072 L 750 138 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 28 360 L 28 1014 L 716 1014 L 716 360 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 46 132 L 46 1068 L 750 1068 L 750 132 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 24 360 L 24 1016 L 732 1016 L 732 360 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 46 118 L 46 1060 L 748 1060 L 748 118 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 26 362 L 26 1026 L 744 1026 L 744 362 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 46 100 L 46 1046 L 744 1046 L 744 100 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 24 354 L 24 1026 L 744 1026 L 744 354 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 44 80 L 44 1042 L 738 1042 L 738 80 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 30 354 L 30 1034 L 758 1034 L 758 354 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 34 84 L 34 1020 L 736 1020 L 736 84 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 30 350 L 30 1030 L 764 1030 L 764 350 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 40 74 L 40 1014 L 744 1014 L 744 74 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 30 348 L 30 1040 L 776 1040 L 776 348 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 40 76 L 40 1016 L 732 1016 L 732 76 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 36 352 L 36 1038 L 784 1038 L 784 352 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 42 60 L 42 1018 L 746 1018 L 746 60 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 34 346 L 34 1034 L 788 1034 L 788 346 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 38 54 L 38 1006 L 736 1006 L 736 54 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 32 344 L 32 1044 L 800 1044 L 800 344 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 38 42 L 38 1020 L 740 1020 L 740 42 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 36 350 L 36 1046 L 802 1046 L 802 350 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 38 52 L 38 1028 L 728 1028 L 728 52 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 36 352 L 36 1062 L 808 1062 L 808 352 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 38 28 L 38 1008 L 726 1008 L 726 28 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 36 346 L 36 1064 L 806 1064 L 806 346 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 38 16 L 38 996 L 722 996 L 722 16 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 36 342 L 36 1062 L 816 1062 L 816 342 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 38 24 L 38 1010 L 704 1010 L 704 24 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 36 332 L 36 1060 L 820 1060 L 820 332 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 38 6 L 38 1010 L 672 1010 L 672 6 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 36 330 L 36 1082 L 808 1082 L 808 330 z" />
			</t2_area>
			<t2_area layer_id="444">
				<t2_path d="M 38 0 L 38 1018 L 660 1018 L 660 0 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 36 332 L 36 1076 L 806 1076 L 806 332 z" />
			</t2_area>
			<t2_area layer_id="447">
				<t2_path d="M 38 8 L 38 1008 L 658 1008 L 658 8 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 34 326 L 34 1074 L 812 1074 L 812 326 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 34 312 L 34 1082 L 808 1082 L 808 312 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 38 298 L 38 1084 L 810 1084 L 810 298 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 38 274 L 38 1092 L 802 1092 L 802 274 z" />
			</t2_area>
			<t2_area layer_id="204">
				<t2_path d="M 30 704 L 30 802 L 242 802 L 242 704 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 40 260 L 40 1116 L 802 1116 L 802 260 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 8 672 L 8 830 L 356 830 L 356 672 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 46 248 L 46 1104 L 816 1104 L 816 248 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 8 612 L 8 858 L 372 858 L 372 612 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 42 238 L 42 1116 L 820 1116 L 820 238 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 0 586 L 0 886 L 396 886 L 396 586 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 42 222 L 42 1102 L 830 1102 L 830 222 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 8 570 L 8 906 L 410 906 L 410 570 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 40 184 L 40 1126 L 842 1126 L 842 184 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 12 540 L 12 918 L 472 918 L 472 540 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 44 186 L 44 1122 L 846 1122 L 846 186 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 12 510 L 12 934 L 490 934 L 490 510 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 44 172 L 44 1124 L 840 1124 L 840 172 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 12 486 L 12 930 L 526 930 L 526 486 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 46 168 L 46 1122 L 840 1122 L 840 168 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 12 472 L 12 942 L 554 942 L 554 472 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 44 178 L 44 1140 L 840 1140 L 840 178 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 10 458 L 10 942 L 572 942 L 572 458 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 44 190 L 44 1098 L 832 1098 L 832 190 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 12 454 L 12 958 L 584 958 L 584 454 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 44 202 L 44 1100 L 828 1100 L 828 202 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 14 450 L 14 958 L 600 958 L 600 450 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 48 190 L 48 1132 L 820 1132 L 820 190 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 16 436 L 16 962 L 612 962 L 612 436 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 46 200 L 46 1118 L 810 1118 L 810 200 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 14 434 L 14 970 L 622 970 L 622 434 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 46 202 L 46 1114 L 808 1114 L 808 202 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 16 420 L 16 972 L 634 972 L 634 420 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 46 202 L 46 1086 L 800 1086 L 800 202 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 18 410 L 18 974 L 652 974 L 652 410 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 46 182 L 46 1094 L 796 1094 L 796 182 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 24 398 L 24 974 L 668 974 L 668 398 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 46 168 L 46 1094 L 786 1094 L 786 168 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 22 386 L 22 980 L 670 980 L 670 386 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="11.0132"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1703.0"
				height="1144.0"
				transform="matrix(0.9999629602998399,0.0019079900471935056,-0.0019079900471935056,0.9999629602998399,605.7630191241878,544.7018386201747)"
				title="Brain10_001_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_001_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1703"
				o_height="1144"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="11.0132"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1703.0"
				height="1159.0"
				transform="matrix(0.9996472755519558,0.021695582082997503,-0.021695582082997503,0.9996472755519558,620.9084661941215,548.3582992322821)"
				title="Brain10_002_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_002_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1703"
				o_height="1159"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="11.0132"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1715.0"
				height="1227.0"
				transform="matrix(0.9920373194486508,-0.12114720635198051,0.12114720635198051,0.9920373194486508,541.2056825198814,701.7581829872092)"
				title="Brain10_003_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_003_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1715"
				o_height="1227"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="11.0132"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1768.0"
				height="1295.0"
				transform="matrix(0.9974160619718538,0.07167018962785518,-0.07167018962785518,0.9974160619718538,584.0979736916277,493.1638452829973)"
				title="Brain10_004_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_004_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1768"
				o_height="1295"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="11.0132"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1768.0"
				height="1295.0"
				transform="matrix(0.9995188180543363,0.030891078150817243,-0.030891078150817243,0.9995188180543363,577.9999732381459,509.876291123937)"
				title="Brain10_005_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_005_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1768"
				o_height="1295"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="11.0132"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1776.0"
				height="1315.0"
				transform="matrix(0.9999112477144265,0.013321633620180563,-0.013321633620180563,0.9999112477144265,562.0072433054415,511.1525573512805)"
				title="Brain10_006_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_006_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1776"
				o_height="1315"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="11.0132"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="26"
				width="1799.0"
				height="1299.0"
				transform="matrix(0.9981463235610641,0.06073703117208774,-0.06073703117208774,0.9981463235610641,571.5558477656402,479.1299175274403)"
				title="Brain10_007_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain10_007_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1799"
				o_height="1299"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="7"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="11.0132"
			 z="88.10560000000001"
			 title="sec#08"
		>
			<t2_patch
				oid="29"
				width="1807.0"
				height="1309.0"