<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain9.xml"
		unuid="1698214047533.773704021.1062956851"
		mipmaps_folder="10x__RGB__x4/trakem2.1698214047533.773704021.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x4/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="651" title="thal" expanded="true">
			<ball id="656" oid="655"/>
			<area_list id="659" oid="658"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="2995.0"
		layer_height="2133.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="655"
			width="1554.0"
			height="738.0"
			transform="matrix(1.0,0.0,0.0,1.0,751.0,577.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="760.0" y="316.0" layer_id="81" r="20.0" />
			<t2_ball_ob x="764.0" y="690.0" layer_id="180" r="20.0" />
			<t2_ball_ob x="754.0" y="246.0" layer_id="216" r="20.0" />
			<t2_ball_ob x="762.0" y="20.0" layer_id="324" r="20.0" />
			<t2_ball_ob x="784.0" y="288.0" layer_id="315" r="20.0" />
			<t2_ball_ob x="50.0" y="508.0" layer_id="366" r="20.0" />
			<t2_ball_ob x="1462.0" y="504.0" layer_id="384" r="20.0" />
			<t2_ball_ob x="20.0" y="718.0" layer_id="318" r="20.0" />
			<t2_ball_ob x="1534.0" y="714.0" layer_id="327" r="20.0" />
		</t2_ball>
		<t2_area_list
			oid="658"
			width="844.0"
			height="972.0"
			transform="matrix(1.0,0.0,0.0,1.0,1483.0,591.0)"
			title="rect"
			links="182,185,188,191,194,197,200,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 34 72 L 34 936 L 722 936 L 722 72 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 40 220 L 40 852 L 734 852 L 734 220 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 34 80 L 34 932 L 730 932 L 730 80 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 40 218 L 40 866 L 744 866 L 744 218 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 34 92 L 34 954 L 736 954 L 736 92 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 44 212 L 44 864 L 742 864 L 742 212 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 32 90 L 32 960 L 730 960 L 730 90 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 42 208 L 42 866 L 756 866 L 756 208 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 26 94 L 26 950 L 726 950 L 726 94 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 42 210 L 42 866 L 768 866 L 768 210 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 22 80 L 22 946 L 730 946 L 730 80 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 44 208 L 44 872 L 778 872 L 778 208 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 22 68 L 22 946 L 728 946 L 728 68 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 46 210 L 46 872 L 778 872 L 778 210 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 22 64 L 22 946 L 730 946 L 730 64 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 50 208 L 50 870 L 784 870 L 784 208 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 16 52 L 16 972 L 730 972 L 730 52 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 50 214 L 50 886 L 788 886 L 788 214 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 14 54 L 14 962 L 726 962 L 726 54 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 52 214 L 52 886 L 798 886 L 798 214 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 10 38 L 10 958 L 722 958 L 722 38 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 54 214 L 54 894 L 798 894 L 798 214 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 14 46 L 14 944 L 722 944 L 722 46 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 54 210 L 54 914 L 802 914 L 802 210 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 14 32 L 14 940 L 724 940 L 724 32 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 46 208 L 46 906 L 802 906 L 802 208 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 10 32 L 10 944 L 714 944 L 714 32 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 52 222 L 52 914 L 806 914 L 806 222 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 4 8 L 4 936 L 710 936 L 710 8 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 50 212 L 50 912 L 800 912 L 800 212 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 4 20 L 4 920 L 704 920 L 704 20 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 50 214 L 50 912 L 794 912 L 794 214 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 10 44 L 10 914 L 708 914 L 708 44 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 48 214 L 48 916 L 802 916 L 802 214 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 6 14 L 6 900 L 654 900 L 654 14 z" />
			</t2_area>
			<t2_area layer_id="180">
				<t2_path d="M 44 486 L 44 606 L 248 606 L 248 486 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 50 208 L 50 918 L 808 918 L 808 208 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 0 2 L 0 944 L 656 944 L 656 2 z" />
			</t2_area>
			<t2_area layer_id="183">
				<t2_path d="M 36 448 L 36 648 L 334 648 L 334 448 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 48 208 L 48 928 L 796 928 L 796 208 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 0 0 L 0 954 L 646 954 L 646 0 z" />
			</t2_area>
			<t2_area layer_id="186">
				<t2_path d="M 34 440 L 34 670 L 360 670 L 360 440 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 50 204 L 50 942 L 798 942 L 798 204 z" />
			</t2_area>
			<t2_area layer_id="189">
				<t2_path d="M 28 418 L 28 682 L 380 682 L 380 418 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 54 196 L 54 936 L 796 936 L 796 196 z" />
			</t2_area>
			<t2_area layer_id="192">
				<t2_path d="M 32 400 L 32 714 L 384 714 L 384 400 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 54 182 L 54 946 L 802 946 L 802 182 z" />
			</t2_area>
			<t2_area layer_id="195">
				<t2_path d="M 36 400 L 36 712 L 402 712 L 402 400 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 54 176 L 54 952 L 812 952 L 812 176 z" />
			</t2_area>
			<t2_area layer_id="198">
				<t2_path d="M 24 398 L 24 740 L 412 740 L 412 398 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 50 164 L 50 954 L 814 954 L 814 164 z" />
			</t2_area>
			<t2_area layer_id="201">
				<t2_path d="M 22 384 L 22 756 L 450 756 L 450 384 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 48 154 L 48 956 L 824 956 L 824 154 z" />
			</t2_area>
			<t2_area layer_id="204">
				<t2_path d="M 24 364 L 24 770 L 478 770 L 478 364 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 52 146 L 52 956 L 832 956 L 832 146 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 22 348 L 22 780 L 502 780 L 502 348 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 48 138 L 48 954 L 834 954 L 834 138 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 20 340 L 20 790 L 518 790 L 518 340 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 48 128 L 48 950 L 832 950 L 832 128 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 16 330 L 16 802 L 540 802 L 540 330 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 48 124 L 48 950 L 830 950 L 830 124 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 18 320 L 18 806 L 560 806 L 560 320 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 48 110 L 48 948 L 844 948 L 844 110 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 22 304 L 22 808 L 566 808 L 566 304 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 40 94 L 40 924 L 816 924 L 816 94 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 22 288 L 22 820 L 576 820 L 576 288 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 42 88 L 42 926 L 804 926 L 804 88 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 28 274 L 28 820 L 604 820 L 604 274 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 42 78 L 42 932 L 802 932 L 802 78 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 28 298 L 28 832 L 624 832 L 624 298 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 40 70 L 40 940 L 788 940 L 788 70 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 30 294 L 30 836 L 636 836 L 636 294 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 42 70 L 42 928 L 792 928 L 792 70 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 32 284 L 32 848 L 646 848 L 646 284 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 46 68 L 46 930 L 782 930 L 782 68 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 34 280 L 34 854 L 648 854 L 648 280 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 44 78 L 44 918 L 778 918 L 778 78 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 32 250 L 32 874 L 674 874 L 674 250 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 40 80 L 40 918 L 762 918 L 762 80 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 36 242 L 36 860 L 682 860 L 682 242 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 42 78 L 42 924 L 760 924 L 760 78 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 36 238 L 36 870 L 688 870 L 688 238 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 38 88 L 38 920 L 738 920 L 738 88 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 44 228 L 44 878 L 696 878 L 696 228 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 34 64 L 34 924 L 732 924 L 732 64 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 42 218 L 42 874 L 704 874 L 704 218 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 34 54 L 34 936 L 730 936 L 730 54 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 40 230 L 40 856 L 716 856 L 716 230 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="11.0132"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1768.0"
				height="1211.0"
				transform="matrix(0.9981651838279815,0.058191514547918245,-0.058191514547918245,0.9981651838279815,680.6138041701926,308.7750400719364)"
				title="Brain9_001_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain9_001_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1768"
				o_height="1211"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.NormalizeLocalContrast" brx="500" bry="500" stds="3.0" cent="true" stret="true" />
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="11.0132"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1768.0"
				height="1225.0"
				transform="matrix(0.9960074666159818,-0.08743606649031287,0.08743606649031287,0.9960074666159818,607.4265433365425,465.22703273198306)"
				title="Brain9_002_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain9_002_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1768"
				o_height="1225"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.NormalizeLocalContrast" brx="500" bry="500" stds="3.0" cent="true" stret="true" />
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="11.0132"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1801.0"
				height="1258.0"
				transform="matrix(0.9995020372932595,0.03139967367876533,-0.03139967367876533,0.9995020372932595,643.3406053802482,328.95975198540907)"
				title="Brain9_003_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain9_003_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1801"
				o_height="1258"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.NormalizeLocalContrast" brx="500" bry="500" stds="3.0" cent="true" stret="true" />
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="11.0132"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1806.0"
				height="1272.0"
				transform="matrix(0.9992553358275454,0.038354113221389714,-0.038354113221389714,0.9992553358275454,648.7973942925262,312.89201109627663)"
				title="Brain9_004_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain9_004_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1806"
				o_height="1272"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.NormalizeLocalContrast" brx="500" bry="500" stds="3.0" cent="true" stret="true" />
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="11.0132"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1849.0"
				height="1272.0"
				transform="matrix(0.9999322871531927,0.01155561061612804,-0.01155561061612804,0.9999322871531927,606.4904701069988,338.4058907583719)"
				title="Brain9_005_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain9_005_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1849"
				o_height="1272"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.NormalizeLocalContrast" brx="500" bry="500" stds="3.0" cent="true" stret="true" />
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="11.0132"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1854.0"
				height="1272.0"
				transform="matrix(0.9995183489697764,0.030993921099842624,-0.030993921099842624,0.9995183489697764,614.4939361119175,302.9601249421696)"
				title="Brain9_006_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain9_006_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1854"
				o_height="1272"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>