<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain6.xml"
		unuid="1683306388420.637324781.1062956851"
		mipmaps_folder="10x__RGB__x4/trakem2.1683306388420.637324781.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x4/"
		mipmaps_format="4"
		n_mipmap_threads="1"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="659" title="thal" expanded="true">
			<area_list id="666" oid="665"/>
			<ball id="668" oid="667"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3127.0"
		layer_height="2316.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_area_list
			oid="665"
			width="821.0"
			height="1080.0"
			transform="matrix(1.0,0.0,0.0,1.0,1550.0,687.0)"
			locked="true"
			title="rect"
			links="170,173,176,179,182,185,188,191,197,200,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 14 38 L 14 1043 L 725 1043 L 725 38 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 35 249 L 35 1005 L 782 1005 L 782 249 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 16 48 L 16 1051 L 724 1051 L 724 48 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 31 255 L 31 1005 L 786 1005 L 786 255 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 18 30 L 18 1047 L 730 1047 L 730 30 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 31 255 L 31 1009 L 784 1009 L 784 255 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 20 26 L 20 1053 L 730 1053 L 730 26 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 31 251 L 31 1013 L 790 1013 L 790 251 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 18 34 L 18 1053 L 730 1053 L 730 34 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 33 251 L 33 1017 L 806 1017 L 806 251 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 18 30 L 18 1045 L 728 1045 L 728 30 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 33 249 L 33 1000 L 800 1000 L 800 249 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 20 42 L 20 1031 L 724 1031 L 724 42 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 33 248 L 33 988 L 804 988 L 804 248 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 12 18 L 12 1023 L 718 1023 L 718 18 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 28 252 L 28 1003 L 802 1003 L 802 252 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 8 10 L 8 1013 L 712 1013 L 712 10 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 28 249 L 28 1004 L 799 1004 L 799 249 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 6 18 L 6 1017 L 706 1017 L 706 18 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 28 249 L 28 1012 L 787 1012 L 787 249 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 4 18 L 4 1011 L 702 1011 L 702 18 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 28 244 L 28 1015 L 787 1015 L 787 244 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 8 4 L 8 1015 L 662 1015 L 662 4 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 28 244 L 28 1020 L 793 1020 L 793 244 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 10 0 L 10 1019 L 658 1019 L 658 0 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 28 244 L 28 1016 L 787 1016 L 787 244 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 0 6 L 0 1017 L 646 1017 L 646 6 z" />
			</t2_area>
			<t2_area layer_id="168">
				<t2_path d="M 93 560 L 93 684 L 277 684 L 277 560 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 28 248 L 28 1036 L 791 1036 L 791 248 z" />
			</t2_area>
			<t2_area layer_id="171">
				<t2_path d="M 59 520 L 59 704 L 333 704 L 333 520 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 28 220 L 28 1037 L 791 1037 L 791 220 z" />
			</t2_area>
			<t2_area layer_id="174">
				<t2_path d="M 52 449 L 52 731 L 404 731 L 404 449 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 24 208 L 24 1041 L 791 1041 L 791 208 z" />
			</t2_area>
			<t2_area layer_id="177">
				<t2_path d="M 47 461 L 47 765 L 423 765 L 423 461 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 24 198 L 24 1044 L 799 1044 L 799 198 z" />
			</t2_area>
			<t2_area layer_id="180">
				<t2_path d="M 44 423 L 44 784 L 449 784 L 449 423 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 29 178 L 29 1053 L 811 1053 L 811 178 z" />
			</t2_area>
			<t2_area layer_id="183">
				<t2_path d="M 44 387 L 44 803 L 478 803 L 478 387 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 25 168 L 25 1052 L 813 1052 L 813 168 z" />
			</t2_area>
			<t2_area layer_id="186">
				<t2_path d="M 44 356 L 44 812 L 492 812 L 492 356 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 23 162 L 23 1060 L 815 1060 L 815 162 z" />
			</t2_area>
			<t2_area layer_id="189">
				<t2_path d="M 40 344 L 40 828 L 532 828 L 532 344 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 29 134 L 29 1049 L 815 1049 L 815 134 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 21 124 L 21 1035 L 821 1035 L 821 124 z" />
			</t2_area>
			<t2_area layer_id="195">
				<t2_path d="M 43 326 L 43 839 L 542 839 L 542 326 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 21 112 L 21 1044 L 815 1044 L 815 112 z" />
			</t2_area>
			<t2_area layer_id="198">
				<t2_path d="M 38 313 L 38 837 L 576 837 L 576 313 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 19 104 L 19 1052 L 811 1052 L 811 104 z" />
			</t2_area>
			<t2_area layer_id="201">
				<t2_path d="M 50 304 L 50 841 L 577 841 L 577 304 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 22 112 L 22 1068 L 805 1068 L 805 112 z" />
			</t2_area>
			<t2_area layer_id="204">
				<t2_path d="M 48 295 L 48 861 L 596 861 L 596 295 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 27 108 L 27 1067 L 801 1067 L 801 108 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 47 291 L 47 872 L 604 872 L 604 291 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 21 87 L 21 1069 L 793 1069 L 793 87 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 47 287 L 47 884 L 616 884 L 616 287 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 30 82 L 30 1080 L 799 1080 L 799 82 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 57 274 L 57 879 L 640 879 L 640 274 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 13 78 L 13 1058 L 777 1058 L 777 78 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 58 268 L 58 888 L 657 888 L 657 268 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 9 94 L 9 1068 L 771 1068 L 771 94 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 53 264 L 53 900 L 660 900 L 660 264 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 9 127 L 9 1064 L 763 1064 L 763 127 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 44 248 L 44 893 L 668 893 L 668 248 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 16 100 L 16 1076 L 757 1076 L 757 100 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 49 252 L 49 915 L 674 915 L 674 252 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 9 90 L 9 1067 L 737 1067 L 737 90 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 43 251 L 43 928 L 694 928 L 694 251 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 9 92 L 9 1061 L 737 1061 L 737 92 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 43 243 L 43 927 L 712 927 L 712 243 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 9 92 L 9 1053 L 743 1053 L 743 92 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 39 257 L 39 901 L 712 901 L 712 257 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 11 82 L 11 1053 L 721 1053 L 721 82 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 104 225 L 104 973 L 720 973 L 720 225 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 11 62 L 11 1060 L 721 1060 L 721 62 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 41 252 L 41 925 L 730 925 L 730 252 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 8 58 L 8 1049 L 726 1049 L 726 58 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 35 247 L 35 975 L 740 975 L 740 247 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 8 54 L 8 1053 L 724 1053 L 724 54 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 35 252 L 35 981 L 762 981 L 762 252 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 12 54 L 12 1047 L 728 1047 L 728 54 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 35 253 L 35 981 L 758 981 L 758 253 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 14 40 L 14 1039 L 728 1039 L 728 40 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 35 256 L 35 987 L 766 987 L 766 256 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 9 84 L 9 1053 L 731 1053 L 731 84 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 35 252 L 35 1004 L 780 1004 L 780 252 z" />
			</t2_area>
		</t2_area_list>
		<t2_ball
			oid="667"
			width="1604.0"
			height="824.0"
			transform="matrix(1.0,0.0,0.0,1.0,766.0,708.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="822.0" y="366.0" layer_id="63" r="20.0" />
			<t2_ball_ob x="842.0" y="800.0" layer_id="165" r="20.0" />
			<t2_ball_ob x="836.0" y="200.0" layer_id="204" r="20.0" />
			<t2_ball_ob x="814.0" y="20.0" layer_id="312" r="20.0" />
			<t2_ball_ob x="808.0" y="298.0" layer_id="306" r="20.0" />
			<t2_ball_ob x="64.0" y="546.0" layer_id="369" r="20.0" />
			<t2_ball_ob x="1492.0" y="578.0" layer_id="366" r="20.0" />
			<t2_ball_ob x="20.0" y="804.0" layer_id="315" r="20.0" />
			<t2_ball_ob x="1584.0" y="772.0" layer_id="312" r="20.0" />
		</t2_ball>
		<t2_layer oid="5"
			 thickness="40.0"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1880.0"
				height="1284.0"
				transform="matrix(0.999826272771402,0.018639320697014128,-0.018639320697014128,0.999826272771402,636.6255371601246,501.47713043206386)"
				locked="true"
				title="Brain6_001_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_001_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1880"
				o_height="1284"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="40.0"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1940.0"
				height="1260.0"
				transform="matrix(0.9969540257407077,0.07799147747924938,-0.07799147747924938,0.9969540257407077,644.5318666080138,415.58093383300775)"
				locked="true"
				title="Brain6_002_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_002_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1940"
				o_height="1260"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="40.0"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1963.0"
				height="1248.0"
				transform="matrix(0.999989881587202,0.004498524559620673,-0.004498524559620673,0.999989881587202,585.9690603204472,503.13401021134996)"
				locked="true"
				title="Brain6_003_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_003_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1963"
				o_height="1248"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="40.0"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1967.0"
				height="1273.0"
				transform="matrix(0.9994609301684606,-0.03283061173349557,0.03283061173349557,0.9994609301684606,563.441585811458,535.0248444633153)"
				locked="true"
				title="Brain6_004_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_004_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1967"
				o_height="1273"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="40.0"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="2009.0"
				height="1302.0"
				transform="matrix(0.9997520567211574,-0.02226713007586293,0.02226713007586293,0.9997520567211574,539.0554532846718,508.47159099988494)"
				locked="true"
				title="Brain6_005_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_005_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2009"
				o_height="1302"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="40.0"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="2009.0"
				height="1302.0"
				transform="matrix(0.994791437740974,-0.10193132686885695,0.10193132686885695,0.994791437740974,495.7157250865821,601.1248379113149)"
				locked="true"
				title="Brain6_006_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_006_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2009"
				o_height="1302"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="40.0"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="26"
				width="2003.0"
				height="1317.0"
				transform="matrix(0.9988975131163071,0.04694420400919598,-0.04694420400919598,0.9988975131163071,598.4999664436982,403.0727524833196)"
				locked="true"
				title="Brain6_007_10x_TdT_YFP__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain6_007_10x_TdT_YFP__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="2003"
				o_height="1317"
				min="0.0"
				max="255.0"