<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain4.xml"
		unuid="1683306289459.637324719.1062956851"
		mipmaps_folder="10x__RGB__x8/trakem2.1683306289459.637324719.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x8/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="479" title="thal" expanded="true">
			<ball id="486" oid="485"/>
			<area_list id="488" oid="487"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3161.0"
		layer_height="2271.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="485"
			width="1628.0"
			height="898.0"
			transform="matrix(1.0,0.0,0.0,1.0,759.0,611.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="784.0" y="500.0" layer_id="105" r="20.0" />
			<t2_ball_ob x="800.0" y="878.0" layer_id="207" r="20.0" />
			<t2_ball_ob x="806.0" y="272.0" layer_id="240" r="20.0" />
			<t2_ball_ob x="808.0" y="20.0" layer_id="351" r="20.0" />
			<t2_ball_ob x="806.0" y="290.0" layer_id="348" r="20.0" />
			<t2_ball_ob x="64.0" y="566.0" layer_id="405" r="20.0" />
			<t2_ball_ob x="1562.0" y="552.0" layer_id="396" r="20.0" />
			<t2_ball_ob x="20.0" y="690.0" layer_id="339" r="20.0" />
			<t2_ball_ob x="1608.0" y="678.0" layer_id="330" r="20.0" />
		</t2_ball>
		<t2_area_list
			oid="487"
			width="850.0"
			height="1052.0"
			transform="matrix(1.0,0.0,0.0,1.0,1549.0,655.0)"
			locked="true"
			title="rect"
			links="212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443,446,449,452,455"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 30 46 L 30 1032 L 778 1032 L 778 46 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 14 250 L 14 888 L 686 888 L 686 250 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 32 18 L 32 1022 L 770 1022 L 770 18 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 14 240 L 14 894 L 696 894 L 696 240 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 30 20 L 30 1030 L 764 1030 L 764 20 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 14 224 L 14 896 L 708 896 L 708 224 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 24 30 L 24 1010 L 752 1010 L 752 30 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 16 222 L 16 902 L 706 902 L 706 222 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 22 42 L 22 1002 L 770 1002 L 770 42 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 20 224 L 20 904 L 732 904 L 732 224 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 28 56 L 28 1004 L 764 1004 L 764 56 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 22 210 L 22 908 L 732 908 L 732 210 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 24 34 L 24 1010 L 762 1010 L 762 34 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 22 200 L 22 894 L 754 894 L 754 200 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 20 34 L 20 1006 L 758 1006 L 758 34 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 26 200 L 26 906 L 768 906 L 768 200 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 24 18 L 24 1018 L 760 1018 L 760 18 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 26 156 L 26 908 L 760 908 L 760 156 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 16 24 L 16 1016 L 754 1016 L 754 24 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 22 184 L 22 912 L 770 912 L 770 184 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 22 18 L 22 1018 L 756 1018 L 756 18 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 22 182 L 22 910 L 770 910 L 770 182 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 30 10 L 30 1014 L 762 1014 L 762 10 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 22 174 L 22 998 L 780 998 L 780 174 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 22 20 L 22 1014 L 760 1014 L 760 20 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 24 182 L 24 920 L 794 920 L 794 182 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 26 10 L 26 1000 L 762 1000 L 762 10 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 22 180 L 22 922 L 800 922 L 800 180 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 28 6 L 28 988 L 768 988 L 768 6 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 22 102 L 22 928 L 802 928 L 802 102 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 28 0 L 28 976 L 764 976 L 764 0 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 32 176 L 32 970 L 808 970 L 808 176 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 26 2 L 26 982 L 766 982 L 766 2 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 30 194 L 30 952 L 824 952 L 824 194 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 30 2 L 30 998 L 768 998 L 768 2 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 32 184 L 32 1002 L 816 1002 L 816 184 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 22 10 L 22 998 L 726 998 L 726 10 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 34 184 L 34 966 L 818 966 L 818 184 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 18 16 L 18 1012 L 738 1012 L 738 16 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 32 188 L 32 972 L 814 972 L 814 188 z" />
			</t2_area>
			<t2_area layer_id="444">
				<t2_path d="M 32 26 L 32 1008 L 724 1008 L 724 26 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 30 130 L 30 1038 L 804 1038 L 804 130 z" />
			</t2_area>
			<t2_area layer_id="447">
				<t2_path d="M 34 38 L 34 1012 L 700 1012 L 700 38 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 28 198 L 28 988 L 812 988 L 812 198 z" />
			</t2_area>
			<t2_area layer_id="450">
				<t2_path d="M 28 36 L 28 1008 L 690 1008 L 690 36 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 28 190 L 28 986 L 812 986 L 812 190 z" />
			</t2_area>
			<t2_area layer_id="453">
				<t2_path d="M 40 30 L 40 992 L 690 992 L 690 30 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 36 174 L 36 1048 L 818 1048 L 818 174 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 32 178 L 32 990 L 820 990 L 820 178 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 30 158 L 30 992 L 834 992 L 834 158 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 30 140 L 30 1052 L 838 1052 L 838 140 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 10 510 L 10 724 L 360 724 L 360 510 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 28 150 L 28 990 L 844 990 L 844 150 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 2 494 L 2 754 L 374 754 L 374 494 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 28 138 L 28 998 L 844 998 L 844 138 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 0 472 L 0 776 L 386 776 L 386 472 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 18 124 L 18 1002 L 850 1002 L 850 124 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 0 440 L 0 790 L 406 790 L 406 440 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 20 110 L 20 1004 L 848 1004 L 848 110 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 4 402 L 4 808 L 436 808 L 436 402 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 20 100 L 20 1010 L 842 1010 L 842 100 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 12 398 L 12 814 L 450 814 L 450 398 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 20 76 L 20 1010 L 844 1010 L 844 76 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 14 338 L 14 824 L 522 824 L 522 338 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 18 64 L 18 1014 L 830 1014 L 830 64 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 14 330 L 14 832 L 544 832 L 544 330 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 16 80 L 16 1016 L 826 1016 L 826 80 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 22 316 L 22 840 L 560 840 L 560 316 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 16 66 L 16 1028 L 812 1028 L 812 66 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 18 302 L 18 844 L 558 844 L 558 302 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 16 68 L 16 1014 L 820 1014 L 820 68 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 20 298 L 20 852 L 578 852 L 578 298 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 14 54 L 14 1016 L 812 1016 L 812 54 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 18 286 L 18 856 L 602 856 L 602 286 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 14 40 L 14 1014 L 806 1014 L 806 40 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 16 276 L 16 864 L 616 864 L 616 276 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 16 44 L 16 1020 L 798 1020 L 798 44 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 12 266 L 12 864 L 628 864 L 628 266 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 20 28 L 20 1022 L 800 1022 L 800 28 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 12 280 L 12 900 L 658 900 L 658 280 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 28 26 L 28 1022 L 798 1022 L 798 26 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 20 260 L 20 864 L 668 864 L 668 260 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="40.0"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1653.0"
				height="1134.0"
				transform="matrix(0.9992060447574425,0.039840684233430686,-0.039840684233430686,0.9992060447574425,754.5225475717853,673.1782691443796)"
				locked="true"
				title="Brain4_001_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_001_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1653"
				o_height="1134"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="40.0"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1643.0"
				height="1174.0"
				transform="matrix(0.9910693533904579,0.1333474288099313,-0.1333474288099313,0.9910693533904579,841.935813524803,561.3282511368448)"
				locked="true"
				title="Brain4_002_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_002_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1643"
				o_height="1174"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="40.0"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1626.0"
				height="1177.0"
				transform="matrix(0.9939590167933597,-0.1097518698482064,0.1097518698482064,0.9939590167933597,727.547447094481,801.4775931849736)"
				locked="true"
				title="Brain4_003_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_003_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1626"
				o_height="1177"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="40.0"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1701.0"
				height="1181.0"
				transform="matrix(0.9949410238972402,0.10046073345497548,-0.10046073345497548,0.9949410238972402,780.6748478017525,583.9796699703302)"
				locked="true"
				title="Brain4_004_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_004_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1701"
				o_height="1181"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="40.0"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1738.0"
				height="1201.0"
				transform="matrix(0.9928897548931879,0.11903753453489052,-0.11903753453489052,0.9928897548931879,762.1950042803492,533.5690490227244)"
				locked="true"
				title="Brain4_005_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_005_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1738"
				o_height="1201"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="40.0"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1717.0"
				height="1225.0"
				transform="matrix(0.9995306716691247,0.03063390919664623,-0.03063390919664623,0.9995306716691247,738.3536656085616,610.2978608879721)"
				locked="true"
				title="Brain4_006_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_006_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1717"
				o_height="1225"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="40.0"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="26"
				width="1788.0"
				height="1225.0"
				transform="matrix(0.9996546768964235,0.026277879653943324,-0.026277879653943324,0.9996546768964235,678.0121592128271,609.0816841901765)"
				locked="true"
				title="Brain4_007_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain4_007_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1788"
				o_height="1225"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="7"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="40.0"
			 z="88.10560000000001"
			 title="sec#08"
		>