<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain8.xml"
		unuid="1698213876310.733847788.1062956851"
		mipmaps_folder="10x__RGB__x4/trakem2.1698213876310.733847788.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x4/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="696" title="thal" expanded="true">
			<ball id="701" oid="700"/>
			<area_list id="704" oid="703"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3127.0"
		layer_height="2090.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="700"
			width="1536.0"
			height="892.0"
			transform="matrix(1.0,0.0,0.0,1.0,814.0,580.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="731.0" y="470.0" layer_id="90" r="20.0" />
			<t2_ball_ob x="743.0" y="872.0" layer_id="204" r="20.0" />
			<t2_ball_ob x="753.0" y="264.0" layer_id="228" r="20.0" />
			<t2_ball_ob x="783.0" y="20.0" layer_id="327" r="20.0" />
			<t2_ball_ob x="777.0" y="306.0" layer_id="330" r="20.0" />
			<t2_ball_ob x="51.0" y="460.0" layer_id="393" r="20.0" />
			<t2_ball_ob x="1465.0" y="498.0" layer_id="390" r="20.0" />
			<t2_ball_ob x="20.0" y="661.0" layer_id="327" r="20.0" />
			<t2_ball_ob x="1516.0" y="653.0" layer_id="324" r="20.0" />
		</t2_ball>
		<t2_area_list
			oid="703"
			width="830.0"
			height="1072.0"
			transform="matrix(1.0,0.0,0.0,1.0,1552.0,499.0)"
			title="rect"
			links="209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 54 110 L 54 1006 L 750 1006 L 750 110 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 18 360 L 18 996 L 668 996 L 668 360 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 52 116 L 52 1014 L 742 1014 L 742 116 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 20 354 L 20 998 L 678 998 L 678 354 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 50 112 L 50 1020 L 738 1020 L 738 112 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 22 342 L 22 1004 L 684 1004 L 684 342 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 44 96 L 44 1006 L 730 1006 L 730 96 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 22 348 L 22 1006 L 700 1006 L 700 348 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 48 84 L 48 1014 L 726 1014 L 726 84 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 24 336 L 24 1016 L 714 1016 L 714 336 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 48 88 L 48 996 L 726 996 L 726 88 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 24 336 L 24 1018 L 720 1018 L 720 336 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 50 70 L 50 994 L 728 994 L 728 70 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 26 338 L 26 1018 L 728 1018 L 728 338 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 48 62 L 48 982 L 728 982 L 728 62 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 30 334 L 30 1026 L 742 1026 L 742 334 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 46 44 L 46 990 L 726 990 L 726 44 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 30 332 L 30 1026 L 740 1026 L 740 332 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 44 34 L 44 1006 L 732 1006 L 732 34 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 30 332 L 30 1022 L 746 1022 L 746 332 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 44 34 L 44 1012 L 730 1012 L 730 34 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 30 328 L 30 1026 L 750 1026 L 750 328 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 42 24 L 42 992 L 726 992 L 726 24 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 30 328 L 30 1026 L 752 1026 L 752 328 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 44 40 L 44 1000 L 732 1000 L 732 40 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 34 318 L 34 1030 L 762 1030 L 762 318 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 42 30 L 42 996 L 740 996 L 740 30 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 34 316 L 34 1020 L 768 1020 L 768 316 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 42 26 L 42 986 L 736 986 L 736 26 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 38 316 L 38 1018 L 770 1018 L 770 316 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 44 14 L 44 990 L 732 990 L 732 14 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 38 314 L 38 1030 L 770 1030 L 770 314 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 38 0 L 38 988 L 724 988 L 724 0 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 38 312 L 38 1032 L 776 1032 L 776 312 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 40 0 L 40 982 L 692 982 L 692 0 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 44 304 L 44 1032 L 776 1032 L 776 304 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 38 0 L 38 994 L 686 994 L 686 0 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 40 296 L 40 1038 L 772 1038 L 772 296 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 34 14 L 34 998 L 678 998 L 678 14 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 40 294 L 40 1042 L 786 1042 L 786 294 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 40 298 L 40 1044 L 778 1044 L 778 298 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 34 292 L 34 1040 L 778 1040 L 778 292 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 42 278 L 42 1038 L 782 1038 L 782 278 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 42 254 L 42 1054 L 792 1054 L 792 254 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 40 236 L 40 1058 L 796 1058 L 796 236 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 44 222 L 44 1054 L 804 1054 L 804 222 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 0 630 L 0 846 L 358 846 L 358 630 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 44 210 L 44 1064 L 808 1064 L 808 210 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 8 602 L 8 876 L 364 876 L 364 602 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 44 192 L 44 1070 L 830 1070 L 830 192 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 2 572 L 2 898 L 388 898 L 388 572 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 50 204 L 50 1072 L 818 1072 L 818 204 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 0 538 L 0 908 L 466 908 L 466 538 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 48 156 L 48 1066 L 822 1066 L 822 156 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 2 526 L 2 920 L 478 920 L 478 526 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 48 144 L 48 1064 L 822 1064 L 822 144 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 2 486 L 2 934 L 502 934 L 502 486 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 48 134 L 48 1048 L 814 1048 L 814 134 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 8 480 L 8 938 L 534 938 L 534 480 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 50 120 L 50 1062 L 802 1062 L 802 120 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 8 462 L 8 950 L 550 950 L 550 462 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 46 134 L 46 1062 L 804 1062 L 804 134 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 4 444 L 4 950 L 570 950 L 570 444 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 48 132 L 48 1046 L 798 1046 L 798 132 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 12 428 L 12 962 L 580 962 L 580 428 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 48 132 L 48 1046 L 796 1046 L 796 132 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 10 426 L 10 966 L 584 966 L 584 426 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 48 140 L 48 1044 L 792 1044 L 792 140 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 10 412 L 10 978 L 596 978 L 596 412 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 44 158 L 44 1044 L 774 1044 L 774 158 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 12 410 L 12 980 L 608 980 L 608 410 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 40 154 L 40 1042 L 774 1042 L 774 154 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 12 394 L 12 976 L 614 976 L 614 394 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 46 142 L 46 1036 L 764 1036 L 764 142 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 16 392 L 16 992 L 616 992 L 616 392 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 52 144 L 52 1030 L 754 1030 L 754 144 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 16 364 L 16 974 L 644 974 L 644 364 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 50 124 L 50 1024 L 744 1024 L 744 124 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 16 362 L 16 986 L 654 986 L 654 362 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="11.0132"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="14"
				width="1763.0"
				height="1228.0"
				transform="matrix(0.9984255521430501,0.05571676209396906,-0.05571676209396906,0.9984255521430501,670.6260347218303,496.46762442780465)"
				title="Brain8_003_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_003_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1763"
				o_height="1228"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="11.0132"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1769.0"
				height="1283.0"
				transform="matrix(0.9989688974556813,-0.045362727531945805,0.045362727531945805,0.9989688974556813,611.5725860228424,602.4179057741745)"
				title="Brain8_002_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_002_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1769"
				o_height="1283"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="11.0132"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="8"
				width="1785.0"
				height="1224.0"
				transform="matrix(0.9999975283911955,-0.0021491559698678044,0.0021491559698678044,0.9999975283911955,638.870273969324,552.0054901074983)"
				title="Brain8_001_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_001_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1785"
				o_height="1224"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="11.0132"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="23"
				width="1838.0"
				height="1290.0"
				transform="matrix(0.9984842273946363,0.052309729516709806,-0.052309729516709806,0.9984842273946363,627.6055782254034,450.6096405959371)"
				title="Brain8_006_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_006_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1838"
				o_height="1290"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="11.0132"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1894.0"
				height="1277.0"
				transform="matrix(0.9999846236341481,-0.005306341243546768,0.005306341243546768,0.9999846236341481,542.2011578013808,529.3359555534229)"
				title="Brain8_005_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_005_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1894"
				o_height="1277"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="11.0132"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="17"
				width="1860.0"
				height="1290.0"
				transform="matrix(0.9998720370683438,-0.015921648025093476,0.015921648025093476,0.9998720370683438,581.7800106772429,552.9113149225293)"
				title="Brain8_004_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_004_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1860"
				o_height="1290"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="11.0132"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="32"
				width="1893.0"
				height="1305.0"
				transform="matrix(0.9999902797642317,0.004306526346025043,-0.004306526346025043,0.9999902797642317,564.2433146639889,505.4442700606238)"
				title="Brain8_009_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_009_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1893"
				o_height="1305"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="9"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="27"
			 thickness="11.0132"
			 z="88.10560000000001"
			 title="sec#08"
		>
			<t2_patch
				oid="29"
				width="1916.0"
				height="1305.0"
				transform="matrix(0.9998994510930973,0.012045137435521434,-0.012045137435521434,0.9998994510930973,560.5964568327424,498.3132771135048)"
				title="Brain8_008_10x__RGB__x4.tif"
				links=""
				type="4"
				file_path="10x__RGB__x4/Brain8_008_10x__RGB__x4.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1916"
				o_height="1305"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="8"
			>