<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain3.xml"
		unuid="1683306234620.637324688.1062956851"
		mipmaps_folder="10x__RGB__x8/trakem2.1683306234620.637324688.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x8/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="507" title="thal" expanded="true">
			<ball id="514" oid="513"/>
			<area_list id="516" oid="515"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3185.0"
		layer_height="2426.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="false"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="513"
			width="1634.0"
			height="884.0"
			transform="matrix(1.0,0.0,0.0,1.0,749.0,692.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="832.0" y="472.0" layer_id="102" r="20.0" />
			<t2_ball_ob x="810.0" y="864.0" layer_id="195" r="20.0" />
			<t2_ball_ob x="806.0" y="298.0" layer_id="240" r="20.0" />
			<t2_ball_ob x="838.0" y="20.0" layer_id="357" r="20.0" />
			<t2_ball_ob x="826.0" y="340.0" layer_id="339" r="20.0" />
			<t2_ball_ob x="98.0" y="590.0" layer_id="396" r="20.0" />
			<t2_ball_ob x="1558.0" y="594.0" layer_id="393" r="20.0" />
			<t2_ball_ob x="20.0" y="782.0" layer_id="336" r="20.0" />
			<t2_ball_ob x="1614.0" y="792.0" layer_id="330" r="20.0" />
		</t2_ball>
		<t2_area_list
			oid="515"
			width="856.0"
			height="1030.0"
			transform="matrix(1.0,0.0,0.0,1.0,1547.0,762.0)"
			locked="true"
			title="rect"
			links="200,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443,446,449,452,455"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 42 8 L 42 1002 L 778 1002 L 778 8 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 6 230 L 6 912 L 672 912 L 672 230 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 44 12 L 44 994 L 754 994 L 754 12 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 10 224 L 10 902 L 694 902 L 694 224 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 46 12 L 46 1000 L 754 1000 L 754 12 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 14 214 L 14 908 L 706 908 L 706 214 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 36 32 L 36 994 L 750 994 L 750 32 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 20 204 L 20 912 L 718 912 L 718 204 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 40 48 L 40 994 L 754 994 L 754 48 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 22 202 L 22 914 L 720 914 L 720 202 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 38 42 L 38 996 L 754 996 L 754 42 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 26 196 L 26 912 L 744 912 L 744 196 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 34 60 L 34 1000 L 750 1000 L 750 60 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 22 198 L 22 924 L 756 924 L 756 198 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 38 64 L 38 998 L 754 998 L 754 64 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 22 186 L 22 932 L 772 932 L 772 186 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 34 50 L 34 994 L 762 994 L 762 50 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 28 198 L 28 940 L 772 940 L 772 198 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 34 60 L 34 1006 L 758 1006 L 758 60 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 24 192 L 24 944 L 766 944 L 766 192 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 40 52 L 40 1000 L 766 1000 L 766 52 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 20 196 L 20 960 L 804 960 L 804 196 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 44 56 L 44 996 L 760 996 L 760 56 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 20 194 L 20 944 L 804 944 L 804 194 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 36 36 L 36 988 L 768 988 L 768 36 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 22 176 L 22 938 L 798 938 L 798 176 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 32 34 L 32 986 L 762 986 L 762 34 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 20 180 L 20 956 L 800 956 L 800 180 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 40 24 L 40 992 L 770 992 L 770 24 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 18 180 L 18 958 L 798 958 L 798 180 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 46 18 L 46 982 L 776 982 L 776 18 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 16 178 L 16 954 L 810 954 L 810 178 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 46 52 L 46 994 L 772 994 L 772 52 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 22 178 L 22 958 L 808 958 L 808 178 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 46 30 L 46 1002 L 784 1002 L 784 30 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 18 174 L 18 968 L 802 968 L 802 174 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 42 14 L 42 1006 L 786 1006 L 786 14 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 24 172 L 24 970 L 798 970 L 798 172 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 48 0 L 48 1014 L 736 1014 L 736 0 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 22 170 L 22 964 L 800 964 L 800 170 z" />
			</t2_area>
			<t2_area layer_id="444">
				<t2_path d="M 48 2 L 48 1004 L 760 1004 L 760 2 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 22 168 L 22 986 L 804 986 L 804 168 z" />
			</t2_area>
			<t2_area layer_id="447">
				<t2_path d="M 48 12 L 48 1000 L 692 1000 L 692 12 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 22 172 L 22 964 L 806 964 L 806 172 z" />
			</t2_area>
			<t2_area layer_id="450">
				<t2_path d="M 40 16 L 40 996 L 692 996 L 692 16 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 22 188 L 22 992 L 802 992 L 802 188 z" />
			</t2_area>
			<t2_area layer_id="453">
				<t2_path d="M 36 20 L 36 996 L 680 996 L 680 20 z" />
			</t2_area>
			<t2_area layer_id="198">
				<t2_path d="M 2 580 L 2 706 L 204 706 L 204 580 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 22 192 L 22 1006 L 800 1006 L 800 192 z" />
			</t2_area>
			<t2_area layer_id="201">
				<t2_path d="M 2 558 L 2 752 L 218 752 L 218 558 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 18 206 L 18 1006 L 808 1006 L 808 206 z" />
			</t2_area>
			<t2_area layer_id="204">
				<t2_path d="M 0 520 L 0 798 L 326 798 L 326 520 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 20 192 L 20 1012 L 818 1012 L 818 192 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 12 470 L 12 796 L 356 796 L 356 470 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 26 176 L 26 1030 L 832 1030 L 832 176 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 2 468 L 2 838 L 368 838 L 368 468 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 26 170 L 26 1012 L 842 1012 L 842 170 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 8 442 L 8 832 L 420 832 L 420 442 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 28 156 L 28 1008 L 850 1008 L 850 156 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 4 426 L 4 846 L 436 846 L 436 426 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 34 146 L 34 1012 L 854 1012 L 854 146 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 12 388 L 12 828 L 472 828 L 472 388 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 38 128 L 38 1008 L 856 1008 L 856 128 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 8 376 L 8 860 L 492 860 L 492 376 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 38 114 L 38 1002 L 854 1002 L 854 114 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 8 354 L 8 860 L 504 860 L 504 354 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 42 100 L 42 1022 L 850 1022 L 850 100 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 2 338 L 2 870 L 516 870 L 516 338 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 36 92 L 36 988 L 844 988 L 844 92 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 2 330 L 2 878 L 532 878 L 532 330 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 44 78 L 44 998 L 838 998 L 838 78 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 4 314 L 4 868 L 546 868 L 546 314 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 42 72 L 42 1010 L 826 1010 L 826 72 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 10 310 L 10 890 L 572 890 L 572 310 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 48 72 L 48 1006 L 822 1006 L 822 72 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 8 308 L 8 890 L 590 890 L 590 308 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 48 56 L 48 1000 L 812 1000 L 812 56 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 10 296 L 10 890 L 606 890 L 606 296 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 54 48 L 54 996 L 816 996 L 816 48 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 4 286 L 4 902 L 620 902 L 620 286 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 54 44 L 54 1000 L 806 1000 L 806 44 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 8 264 L 8 906 L 618 906 L 618 264 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 56 26 L 56 996 L 812 996 L 812 26 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 6 262 L 6 908 L 624 908 L 624 262 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 40 28 L 40 1002 L 798 1002 L 798 28 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 8 232 L 8 904 L 650 904 L 650 232 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="40.0"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1715.0"
				height="1194.0"
				transform="matrix(0.9999999947096258,-1.028627643566265E-4,1.028627643566265E-4,0.9999999947096258,737.4925617902145,657.9095168476288)"
				locked="true"
				title="Brain3_001_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_001_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1715"
				o_height="1194"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="40.0"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1737.0"
				height="1222.0"
				transform="matrix(0.999764332392557,-0.02170897684519078,0.02170897684519078,0.999764332392557,728.0169412101413,678.4484657629332)"
				locked="true"
				title="Brain3_002_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_002_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1737"
				o_height="1222"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="40.0"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1737.0"
				height="1222.0"
				transform="matrix(0.9998435205255337,0.017689953733876457,-0.017689953733876457,0.9998435205255337,734.5207213647554,644.6987896839255)"
				locked="true"
				title="Brain3_003_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_003_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1737"
				o_height="1222"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="40.0"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1786.0"
				height="1238.0"
				transform="matrix(0.9999984610336333,-0.0017544031364494636,0.0017544031364494636,0.9999984610336333,696.7290094147675,637.6485887937574)"
				locked="true"
				title="Brain3_004_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_004_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1786"
				o_height="1238"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="40.0"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1790.0"
				height="1265.0"
				transform="matrix(0.9973551162629173,-0.07268268063426708,0.07268268063426708,0.9973551162629173,656.3750002286652,687.711254609148)"
				locked="true"
				title="Brain3_005_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_005_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1790"
				o_height="1265"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="40.0"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1806.0"
				height="1262.0"
				transform="matrix(0.9999104918553312,-0.01337939750622533,0.01337939750622533,0.9999104918553312,684.513090959179,638.3323052930755)"
				locked="true"
				title="Brain3_006_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_006_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1806"
				o_height="1262"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="24"
			 thickness="40.0"
			 z="77.0924"
			 title="sec#07"
		>
			<t2_patch
				oid="26"
				width="1818.0"
				height="1308.0"
				transform="matrix(0.9937974176628025,-0.11120563226179359,0.11120563226179359,0.9937974176628025,628.021239551992,705.2101498322872)"
				locked="true"
				title="Brain3_007_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain3_007_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1818"
				o_height="1308"