<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ATTLIST project n_mipmap_threads NMTOKEN #REQUIRED>
	<!ATTLIST project n_undo_steps NMTOKEN #REQUIRED>
	<!ATTLIST project look_ahead_cache NMTOKEN #REQUIRED>
	<!ELEMENT anything (ball, area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT ball EMPTY>
	<!ATTLIST ball id NMTOKEN #REQUIRED>
	<!ATTLIST ball oid NMTOKEN #REQUIRED>
	<!ATTLIST ball expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="Brain2.xml"
		unuid="1683306180651.637324657.1062956851"
		mipmaps_folder="10x__RGB__x8/trakem2.1683306180651.637324657.1062956851/trakem2.mipmaps/"
		storage_folder="10x__RGB__x8/"
		mipmaps_format="4"
		n_mipmap_threads="16"
		image_resizing_mode="Area downsampling"
		n_undo_steps="32"
		first_mipmap_level_saved="0"
		look_ahead_cache="0"
	>
		<anything id="479" title="thal" expanded="true">
			<ball id="486" oid="485"/>
			<area_list id="488" oid="487"/>
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="3355.0"
		layer_height="2528.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="3.632005230087531"
			pixelHeight="3.632005230087531"
			pixelDepth="40.0"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_ball
			oid="485"
			width="1704.3334"
			height="778.0"
			transform="matrix(1.0,0.0,0.0,1.0,818.666666666667,668.0)"
			title="fiducials"
			links=""
			layer_set_id="3"
			style="fill:none;stroke-opacity:1.0;stroke:#ffff00;stroke-width:1.0px;"
		>
			<t2_ball_ob x="873.3333333333334" y="410.0" layer_id="87" r="13.333333333333334" />
			<t2_ball_ob x="861.0000000000001" y="764.6666666666667" layer_id="180" r="13.333333333333334" />
			<t2_ball_ob x="852.6666666666667" y="241.66666666666669" layer_id="225" r="13.333333333333334" />
			<t2_ball_ob x="848.3333333333334" y="13.333333333333334" layer_id="342" r="13.333333333333334" />
			<t2_ball_ob x="848.0000000000001" y="318.0" layer_id="333" r="13.333333333333334" />
			<t2_ball_ob x="89.66666666666666" y="639.0" layer_id="381" r="13.333333333333334" />
			<t2_ball_ob x="1585.3333333333333" y="678.0" layer_id="381" r="13.333333333333334" />
			<t2_ball_ob x="13.333333333333334" y="720.0" layer_id="312" r="13.333333333333334" />
			<t2_ball_ob x="1691.0" y="760.0" layer_id="309" r="13.333333333333334" />
		</t2_ball>
		<t2_area_list
			oid="487"
			width="848.0"
			height="1112.0"
			transform="matrix(1.0,0.0,0.0,1.0,1648.0,752.0)"
			locked="true"
			title="rect"
			links="182,185,188,191,194,197,200,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,302,305,308,311,314,317,320,323,326,329,332,335,338,341,344,347,350,353,356,359,362,365,368,371,374,377,380,383,386,389,392,395,398,401,404,407,410,413,416,419,422,425,428,431,434,437,440,443"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="384">
				<t2_path d="M 30 78 L 30 1066 L 766 1066 L 766 78 z" />
			</t2_area>
			<t2_area layer_id="258">
				<t2_path d="M 8 194 L 8 914 L 746 914 L 746 194 z" />
			</t2_area>
			<t2_area layer_id="387">
				<t2_path d="M 30 82 L 30 1064 L 772 1064 L 772 82 z" />
			</t2_area>
			<t2_area layer_id="261">
				<t2_path d="M 6 186 L 6 914 L 760 914 L 760 186 z" />
			</t2_area>
			<t2_area layer_id="390">
				<t2_path d="M 26 74 L 26 1026 L 764 1026 L 764 74 z" />
			</t2_area>
			<t2_area layer_id="264">
				<t2_path d="M 6 178 L 6 920 L 750 920 L 750 178 z" />
			</t2_area>
			<t2_area layer_id="393">
				<t2_path d="M 34 68 L 34 1026 L 764 1026 L 764 68 z" />
			</t2_area>
			<t2_area layer_id="267">
				<t2_path d="M 6 184 L 6 926 L 774 926 L 774 184 z" />
			</t2_area>
			<t2_area layer_id="396">
				<t2_path d="M 34 72 L 34 1044 L 768 1044 L 768 72 z" />
			</t2_area>
			<t2_area layer_id="270">
				<t2_path d="M 0 174 L 0 974 L 774 974 L 774 174 z" />
			</t2_area>
			<t2_area layer_id="399">
				<t2_path d="M 32 58 L 32 1076 L 728 1076 L 728 58 z" />
			</t2_area>
			<t2_area layer_id="273">
				<t2_path d="M 2 180 L 2 1010 L 782 1010 L 782 180 z" />
			</t2_area>
			<t2_area layer_id="402">
				<t2_path d="M 32 24 L 32 1076 L 770 1076 L 770 24 z" />
			</t2_area>
			<t2_area layer_id="276">
				<t2_path d="M 6 176 L 6 982 L 772 982 L 772 176 z" />
			</t2_area>
			<t2_area layer_id="405">
				<t2_path d="M 38 20 L 38 1034 L 770 1034 L 770 20 z" />
			</t2_area>
			<t2_area layer_id="279">
				<t2_path d="M 10 182 L 10 986 L 786 986 L 786 182 z" />
			</t2_area>
			<t2_area layer_id="408">
				<t2_path d="M 34 44 L 34 1054 L 760 1054 L 760 44 z" />
			</t2_area>
			<t2_area layer_id="282">
				<t2_path d="M 10 178 L 10 1012 L 800 1012 L 800 178 z" />
			</t2_area>
			<t2_area layer_id="411">
				<t2_path d="M 34 48 L 34 1052 L 776 1052 L 776 48 z" />
			</t2_area>
			<t2_area layer_id="285">
				<t2_path d="M 10 172 L 10 1008 L 804 1008 L 804 172 z" />
			</t2_area>
			<t2_area layer_id="414">
				<t2_path d="M 38 44 L 38 1038 L 776 1038 L 776 44 z" />
			</t2_area>
			<t2_area layer_id="288">
				<t2_path d="M 10 176 L 10 1006 L 822 1006 L 822 176 z" />
			</t2_area>
			<t2_area layer_id="417">
				<t2_path d="M 38 38 L 38 1048 L 774 1048 L 774 38 z" />
			</t2_area>
			<t2_area layer_id="291">
				<t2_path d="M 16 166 L 16 1036 L 822 1036 L 822 166 z" />
			</t2_area>
			<t2_area layer_id="420">
				<t2_path d="M 46 18 L 46 1048 L 768 1048 L 768 18 z" />
			</t2_area>
			<t2_area layer_id="294">
				<t2_path d="M 12 176 L 12 1010 L 830 1010 L 830 176 z" />
			</t2_area>
			<t2_area layer_id="423">
				<t2_path d="M 38 20 L 38 1038 L 758 1038 L 758 20 z" />
			</t2_area>
			<t2_area layer_id="297">
				<t2_path d="M 14 186 L 14 1030 L 816 1030 L 816 186 z" />
			</t2_area>
			<t2_area layer_id="426">
				<t2_path d="M 38 28 L 38 1044 L 758 1044 L 758 28 z" />
			</t2_area>
			<t2_area layer_id="300">
				<t2_path d="M 12 176 L 12 1030 L 812 1030 L 812 176 z" />
			</t2_area>
			<t2_area layer_id="429">
				<t2_path d="M 26 34 L 26 1034 L 748 1034 L 748 34 z" />
			</t2_area>
			<t2_area layer_id="303">
				<t2_path d="M 20 182 L 20 1030 L 788 1030 L 788 182 z" />
			</t2_area>
			<t2_area layer_id="432">
				<t2_path d="M 38 24 L 38 1062 L 734 1062 L 734 24 z" />
			</t2_area>
			<t2_area layer_id="306">
				<t2_path d="M 20 182 L 20 1054 L 818 1054 L 818 182 z" />
			</t2_area>
			<t2_area layer_id="435">
				<t2_path d="M 42 36 L 42 1066 L 700 1066 L 700 36 z" />
			</t2_area>
			<t2_area layer_id="180">
				<t2_path d="M 52 468 L 52 614 L 198 614 L 198 468 z" />
			</t2_area>
			<t2_area layer_id="309">
				<t2_path d="M 20 180 L 20 1048 L 818 1048 L 818 180 z" />
			</t2_area>
			<t2_area layer_id="438">
				<t2_path d="M 42 38 L 42 1048 L 686 1048 L 686 38 z" />
			</t2_area>
			<t2_area layer_id="183">
				<t2_path d="M 36 500 L 36 616 L 210 616 L 210 500 z" />
			</t2_area>
			<t2_area layer_id="312">
				<t2_path d="M 20 168 L 20 1054 L 802 1054 L 802 168 z" />
			</t2_area>
			<t2_area layer_id="441">
				<t2_path d="M 42 0 L 42 1036 L 680 1036 L 680 0 z" />
			</t2_area>
			<t2_area layer_id="186">
				<t2_path d="M 16 492 L 16 624 L 302 624 L 302 492 z" />
			</t2_area>
			<t2_area layer_id="315">
				<t2_path d="M 20 192 L 20 1052 L 820 1052 L 820 192 z" />
			</t2_area>
			<t2_area layer_id="189">
				<t2_path d="M 10 468 L 10 638 L 396 638 L 396 468 z" />
			</t2_area>
			<t2_area layer_id="318">
				<t2_path d="M 22 192 L 22 1062 L 832 1062 L 832 192 z" />
			</t2_area>
			<t2_area layer_id="192">
				<t2_path d="M 24 430 L 24 688 L 428 688 L 428 430 z" />
			</t2_area>
			<t2_area layer_id="321">
				<t2_path d="M 26 164 L 26 1048 L 824 1048 L 824 164 z" />
			</t2_area>
			<t2_area layer_id="195">
				<t2_path d="M 24 400 L 24 712 L 430 712 L 430 400 z" />
			</t2_area>
			<t2_area layer_id="324">
				<t2_path d="M 16 170 L 16 1048 L 836 1048 L 836 170 z" />
			</t2_area>
			<t2_area layer_id="198">
				<t2_path d="M 20 402 L 20 740 L 468 740 L 468 402 z" />
			</t2_area>
			<t2_area layer_id="327">
				<t2_path d="M 16 166 L 16 1068 L 846 1068 L 846 166 z" />
			</t2_area>
			<t2_area layer_id="201">
				<t2_path d="M 12 382 L 12 766 L 486 766 L 486 382 z" />
			</t2_area>
			<t2_area layer_id="330">
				<t2_path d="M 16 146 L 16 1044 L 842 1044 L 842 146 z" />
			</t2_area>
			<t2_area layer_id="204">
				<t2_path d="M 16 370 L 16 744 L 488 744 L 488 370 z" />
			</t2_area>
			<t2_area layer_id="333">
				<t2_path d="M 18 144 L 18 1044 L 836 1044 L 836 144 z" />
			</t2_area>
			<t2_area layer_id="207">
				<t2_path d="M 30 338 L 30 778 L 522 778 L 522 338 z" />
			</t2_area>
			<t2_area layer_id="336">
				<t2_path d="M 24 124 L 24 1060 L 840 1060 L 840 124 z" />
			</t2_area>
			<t2_area layer_id="210">
				<t2_path d="M 28 326 L 28 796 L 544 796 L 544 326 z" />
			</t2_area>
			<t2_area layer_id="339">
				<t2_path d="M 24 108 L 24 1052 L 840 1052 L 840 108 z" />
			</t2_area>
			<t2_area layer_id="213">
				<t2_path d="M 34 302 L 34 806 L 556 806 L 556 302 z" />
			</t2_area>
			<t2_area layer_id="342">
				<t2_path d="M 24 106 L 24 1038 L 848 1038 L 848 106 z" />
			</t2_area>
			<t2_area layer_id="216">
				<t2_path d="M 36 284 L 36 810 L 580 810 L 580 284 z" />
			</t2_area>
			<t2_area layer_id="345">
				<t2_path d="M 28 100 L 28 1056 L 842 1056 L 842 100 z" />
			</t2_area>
			<t2_area layer_id="219">
				<t2_path d="M 32 272 L 32 810 L 594 810 L 594 272 z" />
			</t2_area>
			<t2_area layer_id="348">
				<t2_path d="M 44 106 L 44 1072 L 846 1072 L 846 106 z" />
			</t2_area>
			<t2_area layer_id="222">
				<t2_path d="M 28 264 L 28 822 L 610 822 L 610 264 z" />
			</t2_area>
			<t2_area layer_id="351">
				<t2_path d="M 32 114 L 32 1088 L 804 1088 L 804 114 z" />
			</t2_area>
			<t2_area layer_id="225">
				<t2_path d="M 26 262 L 26 830 L 618 830 L 618 262 z" />
			</t2_area>
			<t2_area layer_id="354">
				<t2_path d="M 30 104 L 30 1094 L 820 1094 L 820 104 z" />
			</t2_area>
			<t2_area layer_id="228">
				<t2_path d="M 26 236 L 26 842 L 624 842 L 624 236 z" />
			</t2_area>
			<t2_area layer_id="357">
				<t2_path d="M 34 100 L 34 1086 L 820 1086 L 820 100 z" />
			</t2_area>
			<t2_area layer_id="231">
				<t2_path d="M 24 248 L 24 842 L 644 842 L 644 248 z" />
			</t2_area>
			<t2_area layer_id="360">
				<t2_path d="M 34 72 L 34 1076 L 818 1076 L 818 72 z" />
			</t2_area>
			<t2_area layer_id="234">
				<t2_path d="M 24 230 L 24 846 L 670 846 L 670 230 z" />
			</t2_area>
			<t2_area layer_id="363">
				<t2_path d="M 24 68 L 24 1086 L 800 1086 L 800 68 z" />
			</t2_area>
			<t2_area layer_id="237">
				<t2_path d="M 24 216 L 24 848 L 684 848 L 684 216 z" />
			</t2_area>
			<t2_area layer_id="366">
				<t2_path d="M 22 74 L 22 1106 L 796 1106 L 796 74 z" />
			</t2_area>
			<t2_area layer_id="240">
				<t2_path d="M 22 210 L 22 860 L 702 860 L 702 210 z" />
			</t2_area>
			<t2_area layer_id="369">
				<t2_path d="M 26 68 L 26 1108 L 794 1108 L 794 68 z" />
			</t2_area>
			<t2_area layer_id="243">
				<t2_path d="M 22 206 L 22 872 L 702 872 L 702 206 z" />
			</t2_area>
			<t2_area layer_id="372">
				<t2_path d="M 22 60 L 22 1112 L 790 1112 L 790 60 z" />
			</t2_area>
			<t2_area layer_id="246">
				<t2_path d="M 20 204 L 20 840 L 708 840 L 708 204 z" />
			</t2_area>
			<t2_area layer_id="375">
				<t2_path d="M 32 64 L 32 1108 L 782 1108 L 782 64 z" />
			</t2_area>
			<t2_area layer_id="249">
				<t2_path d="M 26 192 L 26 882 L 732 882 L 732 192 z" />
			</t2_area>
			<t2_area layer_id="378">
				<t2_path d="M 30 72 L 30 1068 L 772 1068 L 772 72 z" />
			</t2_area>
			<t2_area layer_id="252">
				<t2_path d="M 26 198 L 26 878 L 732 878 L 732 198 z" />
			</t2_area>
			<t2_area layer_id="381">
				<t2_path d="M 26 68 L 26 1084 L 756 1084 L 756 68 z" />
			</t2_area>
			<t2_area layer_id="255">
				<t2_path d="M 20 194 L 20 894 L 736 894 L 736 194 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="40.0"
			 z="11.013200000000001"
			 title="sec#01"
		>
			<t2_patch
				oid="8"
				width="1861.0"
				height="1334.0"
				transform="matrix(0.9974997466125777,0.07067004675138637,-0.07067004675138637,0.9974997466125777,785.3371375389697,399.36828187592073)"
				locked="true"
				title="Brain2_001_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain2_001_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1861"
				o_height="1334"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="1"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="9"
			 thickness="40.0"
			 z="22.026400000000002"
			 title="sec#02"
		>
			<t2_patch
				oid="11"
				width="1893.0"
				height="1299.0"
				transform="matrix(0.9927927604504466,0.11984379331939583,-0.11984379331939583,0.9927927604504466,782.9559658180715,386.5201862736503)"
				locked="true"
				title="Brain2_002_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain2_002_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1893"
				o_height="1299"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="2"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="12"
			 thickness="40.0"
			 z="33.0396"
			 title="sec#03"
		>
			<t2_patch
				oid="14"
				width="1836.0"
				height="1369.0"
				transform="matrix(0.9949580256189552,-0.10029220935063062,0.10029220935063062,0.9949580256189552,720.8016020935502,549.5946982437445)"
				locked="true"
				title="Brain2_003_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain2_003_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1836"
				o_height="1369"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="3"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="15"
			 thickness="40.0"
			 z="44.052800000000005"
			 title="sec#04"
		>
			<t2_patch
				oid="17"
				width="1902.0"
				height="1338.0"
				transform="matrix(0.9943843318233377,0.1058291104765323,-0.1058291104765323,0.9943843318233377,778.8947832516978,362.373750966452)"
				locked="true"
				title="Brain2_004_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain2_004_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1902"
				o_height="1338"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="4"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="18"
			 thickness="40.0"
			 z="55.066"
			 title="sec#05"
		>
			<t2_patch
				oid="20"
				width="1902.0"
				height="1401.0"
				transform="matrix(0.9783533497795085,0.20694135153519835,-0.20694135153519835,0.9783533497795085,858.8570523051694,236.14079861278242)"
				locked="true"
				title="Brain2_005_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain2_005_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1902"
				o_height="1401"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="5"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />
				<t2_prop key="cal" value="3.6320052301" />
			</t2_patch>
		</t2_layer>
		<t2_layer oid="21"
			 thickness="40.0"
			 z="66.0792"
			 title="sec#06"
		>
			<t2_patch
				oid="23"
				width="1941.0"
				height="1418.0"
				transform="matrix(0.9881800221185953,0.15329789263291457,-0.15329789263291457,0.9881800221185953,800.7750009197634,268.21116873109304)"
				locked="true"
				title="Brain2_006_10x_TdT_YFP__RGB__x8.tif"
				links=""
				type="4"
				file_path="10x__RGB__x8/Brain2_006_10x_TdT_YFP__RGB__x8.tif"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="1941"
				o_height="1418"
				min="0.0"
				max="255.0"
				mres="32"
				alpha_mask_id="6"
			>
				<t2_filter class="ini.trakem2.imaging.filters.CLAHE" fast="true" blockradius="63" bins="255" slope="3.0" />
				<t2_prop key="unit" value="µm" />